### PR TITLE
feat(splash): add splash screen and tailwindcss

### PR DESCRIPTION
**Pull request by dylanbathurst**
image

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
Thanks for posting the screenshot. It LGTM. 

Also @Evanfeenstra we have a comment on styling libraries from Dylan in the issue: "Some things we may want to consider for the future are styling libraries. I prefer and used tailwindcss for this extension as it allows really rapid development. I also used the svg icons from the figma file, but we may want to consider using an icon library like feather icons or others, but it's totally fine if we use the ones in figma as well." 

I think we can just use icons from figma for now as this is just an MVP. But you can make the final call.

https://github.com/stakwork/sphinx-js/issues/5#issuecomment-1853209541

**Comment by Evanfeenstra** [comment]
tailwind is fine w me. Using the SVGs is fine as well, its a simple UI so there won't be tons of icons

LGTM!

**Comment by ecurrencyhodler** [comment]
Okay let's use tailwind. @dylanbathurst do you need me to create a separate issue for this?

also I'm paying you out now.

**Comment by dylanbathurst** [comment]
No need for a new issue. It's already done. Thanks!

**Pull request merged**
